### ISSUE TITLE
OData handler does not use metadata file

### ISSUE THREAD

**Issue by FH-Inway** [charlypoly/graphql-mesh-docs-first-gateway#9] opened 2022-08-13 16:35 UTC
I took my first steps with GraphQL Mesh today, great solution so far!

I tried to add the TripPin OData API to the multiple-sources example, using the following source declaration in .meshrc.yaml:
```
- name: TripPin
    handler:
      odata:
        baseUrl: https://services.odata.org/TripPinRESTierService/(S(qzsyox3345c15qeq305pblvw))/
        metadata: C:\Temp\graphql-mesh-docs-first-gateway\packages\multiple-sources\Tripin.xml
```
The Tripin.xml file was obtained from https://services.odata.org/TripPinRESTierService/$metadata

When running `yarn start-multiple-sources`, it gives me an error:
> Failed to generate the schema TypeError: config.fetch is not a function

The stack trace starts at `readUrl`, so despite specifying a metadata file, it still tries to retrieve the metadata from the url.
To force the use of the metadata file, I changed the `isURL` function to always return false.
With this change, multiple-sources runs successful and I can see the TripPin nodes in GraphiQL explorer (I removed the filter that only shows `Query.stores`).

My environment is Windows Server 2019, npm, yarn, ... was all installed today, so should be on the latest version.

Here is the full output from `yarn start-multiple-sources` with the error:

> C:\Temp\graphql-mesh-docs-first-gateway\packages [master ≡ +2 ~12 -0 !]> yarn start-multiple-sources
yarn run v1.22.19
$ concurrently --kill-others "yarn workspace authors-service start" "yarn workspace stores-service start"  "yarn workspace books-service start"  "yarn workspace mesh-multiple-sources start"
$ node dist/index.js
$ node dist/index.js
$ nest start
$ mesh dev
[0] server is running on 0.0.0.0:3003
[1] 🧘 Yoga - 💡 GraphQL Server running at http://127.0.0.1:3004/graphql.
[3] 🕸️ - Server : Generating the unified schema...
[3] 🕸️ - TripPin : Failed to generate the schema TypeError: config.fetch is not a function
[3]     at readUrl (C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\odata\node_modules\@graphql-mesh\utils\index.js:184:35)
[3]     at Object.readFileOrUrl (C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\odata\node_modules\@graphql-mesh\utils\index.js:95:16)
[3]     at C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\odata\index.js:95:46
[3]     at Object.getWithSet (C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\store\index.js:151:44)
[3]     at async ODataHandler.getMeshSource (C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\odata\index.js:120:30)
[3]     at async C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\runtime\index.js:39:28
[3]     at async Promise.allSettled (index 3)
[3]     at async Object.getMesh (C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\runtime\index.js:34:5)
[3] (node:9628) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
[3] (Use `node --trace-warnings ...` to show where the warning was created)
[3] 🕸️ : An error occured while writing the schema file: Error: Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 environmental variable to get more verbose output.
[3]     at Object.getMesh (C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\runtime\index.js:69:15)
[3] 🕸️ : An error occurred while building the artifacts: Error: Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 environmental variable to get more verbose output.
[3]     at Object.getMesh (C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\runtime\index.js:69:15)
[3] 🕸️ - Server : Error: Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 environmental variable to get more verbose output.
[3]     at Object.getMesh (C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\runtime\index.js:69:15)
[3] Error: Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 environmental variable to get more verbose output.
[3]     at Object.getMesh (C:\Temp\graphql-mesh-docs-first-gateway\node_modules\@graphql-mesh\runtime\index.js:69:15)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
error Command failed.
[3] Exit code: 1
[3] Command: C:\Program Files\nodejs\node.exe
[3] Arguments: C:\Program Files (x86)\Yarn\lib\cli.js start
[3] Directory: C:\Temp\graphql-mesh-docs-first-gateway\packages\multiple-sources
[3] Output:
[3]
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
[3] yarn workspace mesh-multiple-sources start exited with code 1
--> Sending SIGTERM to other processes..
[0] yarn workspace authors-service start exited with code 1
--> Sending SIGTERM to other processes..
[1] yarn workspace stores-service start exited with code 1
--> Sending SIGTERM to other processes..
[2] yarn workspace books-service start exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ardatan** [comment] 2022-08-17 14:31
Could you share a reproduction on CodeSandbox or StackBlitz? Thanks!

**Comment by FH-Inway** [comment] 2022-08-18 20:28
Thanks for taking a look. I'm not familiar with either CodeSandbox or StackBlitz, so it might take some time. Is there a guide how the examples from this repo can be deployed on either of them?

**Comment by ardatan** [comment] 2022-08-19 01:56
You can setup a project like you do in your local environment.

**Comment by ardatan** [comment] 2023-08-23 11:06
Closing this issue since this is not relevant to this repo. If you still have issues, you can create an issue in graphql-mesh repository.

**Closed** 2023-08-23 11:05 UTC
