### ISSUE TITLE
Please Clarify: How to Use Programmatic Resolvers?

### ISSUE THREAD

**Issue by sraza-onshape** [charlypoly/graphql-mesh-docs-first-gateway#30] opened 2023-05-09 19:18 UTC
Hello,

I have been studying the example provided in the "[Combine multiple Sources](https://the-guild.dev/graphql/mesh/docs/getting-started/combine-multiple-sources)" guide, which is accompanied by the [`packages/multiple-sources-prog-resolvers`](https://github.com/charlypoly/graphql-mesh-docs-first-gateway/tree/master/packages/multiple-sources-prog-resolvers) code in this repo. 

I have a similar use case for GQL Mesh where I am trying to setup a nested hierarchy between types - but I would like some input, to help double check if I really understand how this library works:

1.  In the example I linked above, one of the hierarchies that gets added into the gateway is for the `Book` type. It [initially has a field called `authorId`](https://github.com/charlypoly/graphql-mesh-docs-first-gateway/blob/master/packages/multiple-sources-prog-resolvers/.mesh/sources/Books/schema.graphql#L36), and gets [an additional field called `author`. ](https://github.com/charlypoly/graphql-mesh-docs-first-gateway/blob/master/packages/multiple-sources-prog-resolvers/.mesh/schema.graphql#L5).
2. **First question**: in the `resolvers.ts`, I can see we set the `selectionSet` to contain the `authorId`. I would like to know exactly [why this line is required](https://github.com/charlypoly/graphql-mesh-docs-first-gateway/blob/master/packages/multiple-sources-prog-resolvers/resolvers.ts#L8) - like, is it to let GQL Mesh know that when we provide it an `id`, it should understand that to be an `authorId`, and thereby go about retrieving the appropriate `author` successfully?
3. **Second question**: on a related note, how would the implementation of this resolver function change, if we did not have a the `authorId` field on `Book`? Like, how would we potentially pass in that arg through another means, e.g. the `_args` object?
4. **Third question**: what does it mean if my GQL mesh generates a `QuerySdk` type for me (which, I suppose can be used to implement an `additionalResolver`, yet there's a comment in its body that says `/** null **/`? 

Here's what I mean as an example - does null comment mean my `InContextSdkMethod` will always return `null`, no matter what?
```
// services/gateway/.mesh/sources/someServiceName/types.ts
export type QuerySdk = {
      /** null **/
  someFieldName: InContextSdkMethod<Query['someFieldName'], QuerysomeFieldNameArgs, MeshContext>
  };
```

Thanks in advance for your help!

**Comment by ardatan** [comment] 2023-08-23 11:17
> First question: in the resolvers.ts, I can see we set the selectionSet to contain the authorId. I would like to know exactly [why this line is required](https://github.com/charlypoly/graphql-mesh-docs-first-gateway/blob/master/packages/multiple-sources-prog-resolvers/resolvers.ts#L8) - like, is it to let GQL Mesh know that when we provide it an id, it should understand that to be an authorId, and thereby go about retrieving the appropriate author successfully?

`selectionSet` means the least required selection needed for that additional resolver.
We need `authorId` in order to get author. 

>on a related note, how would the implementation of this resolver function change, if we did not have a the authorId field on Book? Like, how would we potentially pass in that arg through another means, e.g. the _args object?

The only way of doing that is to use `selectionSet`

> what does it mean if my GQL mesh generates a QuerySdk type for me (which, I suppose can be used to implement an additionalResolver, yet there's a comment in its body that says /** null **/?

We need a reproduction for that to answer. I don't have much idea why it has `null`.

Closing this issue since it is a Q&A :) We can keep the conversation here.

**Closed by ardatan** 2023-08-23 11:17 UTC
